### ISSUE TITLE
Licence of forked work

### ISSUE THREAD

**Issue by joekickass** [robotika/jessica#1]
Hello,

I have forked the repository robotika/jessica and loosely based my btsnoop parser on it, see joekickass/btsnoop. I have added a MIT license for my added code, but since the original code forked from your repository is missing a license, I do not know how to license that. I could simply rewrite the small part that is left from the fork, but I much prefer to give you credit. Is it possible for you to add a license to robotika/jessica?

**Comment by m3d** [comment]
Fixed:
https://github.com/robotika/jessica/commit/28e9774d89e2f2c77f2902df5ec0c65c1b529566
sorry about that
thanks
   Martin

**Comment by joekickass** [comment]
Thank you, I have now updated the license in my rework
